interface Category {
    href: string;
    name: string;
    icon: string;
}
interface Category {
    id: number;
    href: string;
    name: string;
    icon: string;
}
export const categories: Category[] = [
    { id: 1, name: "National Parks", href: "/national-parks", icon: "/images/nav-icons/national-parks.jpg" },
    { id: 2, name: "Icons", href: "/icons", icon: "/images/nav-icons/icons.jpg" },
    { id: 3, name: "Countryside", href: "/countryside", icon: "/images/nav-icons/countryside.jpg" },
    { id: 4, name: "Tiny Homes", href: "/tiny-homes", icon: "/images/nav-icons/tiny-homes.jpg" },
    { id: 5, name: "Cabins", href: "/cabins", icon: "/images/nav-icons/cabins.jpg" },
    { id: 6, name: "Trending", href: "/trending", icon: "/images/nav-icons/trending.jpg" },
    { id: 7, name: "OMG!", href: "/omg", icon: "/images/nav-icons/omg.jpg" },
    { id: 8, name: "Castles", href: "/castles", icon: "/images/nav-icons/castles.jpg" },
    { id: 9, name: "Amazing pools", href: "/amazing-pools", icon: "/images/nav-icons/amazing-pools.jpg" },
    { id: 10, name: "Amazing Views", href: "/amazing-views", icon: "/images/nav-icons/amazing-views.jpg" },
    { id: 11, name: "Ski-in/out", href: "/ski-in-out", icon: "/images/nav-icons/ski-in-out.jpg" },
    { id: 12, name: "Beachfront", href: "/beachfront", icon: "/images/nav-icons/beachfront.jpg" },
    { id: 13, name: "Treehouses", href: "/treehouses", icon: "/images/nav-icons/treehouses.jpg" },
    { id: 14, name: "Off-the-grid", href: "/off-the-grid", icon: "/images/nav-icons/off-the-grid.jpg" },
    { id: 15, name: "Farms", href: "/farms", icon: "/images/nav-icons/farms.jpg" },
    { id: 16, name: "Mansions", href: "/mansions", icon: "/images/nav-icons/mansions.jpg" },
    { id: 17, name: "Islands", href: "/islands", icon: "/images/nav-icons/islands.jpg" },
    { id: 18, name: "Design", href: "/design", icon: "/images/nav-icons/design.jpg" },
    { id: 19, name: "Lakefront", href: "/lakefront", icon: "/images/nav-icons/lakefront.jpg" },
    { id: 20, name: "Lake", href: "/lake", icon: "/images/nav-icons/lake.jpg" },
    { id: 21, name: "Houseboats", href: "/houseboats", icon: "/images/nav-icons/houseboats.jpg" },
    { id: 22, name: "Luxe", href: "/luxe", icon: "/images/nav-icons/luxe.jpg" },
    { id: 23, name: "Bed & breakfasts", href: "/bed-breakfasts", icon: "/images/nav-icons/bed-breakfasts.jpg" },
    { id: 24, name: "Boats", href: "/boats", icon: "/images/nav-icons/boats.jpg" },
    { id: 25, name: "Play", href: "/play", icon: "/images/nav-icons/play.jpg" },
    { id: 26, name: "Historical homes", href: "/historical-homes", icon: "/images/nav-icons/historical-homes.jpg" },
    { id: 27, name: "Tropical", href: "/tropical", icon: "/images/nav-icons/tropical.jpg" },
    { id: 28, name: "Earth homes", href: "/earth-homes", icon: "/images/nav-icons/earth-homes.jpg" },
    { id: 29, name: "Domes", href: "/domes", icon: "/images/nav-icons/domes.jpg" },
    { id: 30, name: "A-farmse", href: "/a-farmse", icon: "/images/nav-icons/a-farmse.jpg" },
    { id: 31, name: "Barns", href: "/barns", icon: "/images/nav-icons/barns.jpg" },
    { id: 32, name: "Top cities", href: "/top-cities", icon: "/images/nav-icons/top-cities.jpg" },
    { id: 33, name: "Vineyards", href: "/vineyards", icon: "/images/nav-icons/vineyards.jpg" },
    { id: 34, name: "Arctic", href: "/arctic", icon: "/images/nav-icons/arctic.jpg" },
    { id: 35, name: "Yurts", href: "/yurts", icon: "/images/nav-icons/yurts.jpg" },
    { id: 36, name: "Creative spaces", href: "/creative-spaces", icon: "/images/nav-icons/creative-spaces.jpg" },
    { id: 37, name: "Grand pianos", href: "/grand-pianos", icon: "/images/nav-icons/grand-pianos.jpg" },
    { id: 38, name: "Camping", href: "/camping", icon: "/images/nav-icons/camping.jpg" },
    { id: 39, name: "Top of the world", href: "/top-of-the-world", icon: "/images/nav-icons/top-of-the-world.jpg" },
    { id: 40, name: "New", href: "/new", icon: "/images/nav-icons/new.jpg" },
    { id: 41, name: "Caves", href: "/caves", icon: "/images/nav-icons/caves.jpg" },
    { id: 42, name: "Towers", href: "/towers", icon: "/images/nav-icons/towers.jpg" },
    { id: 43, name: "Rooms", href: "/rooms", icon: "/images/nav-icons/rooms.jpg" },
    { id: 44, name: "Cycladic homes", href: "/cycladic-homes", icon: "/images/nav-icons/cycladic-homes.jpg" },
    { id: 45, name: "Chef's kitchens", href: "/chefs-kitchens", icon: "/images/nav-icons/chefs-kitchens.jpg" },
    { id: 46, name: "Windmills", href: "/windmills", icon: "/images/nav-icons/windmills.jpg" },
    { id: 47, name: "Containers", href: "/containers", icon: "/images/nav-icons/containers.jpg" },
    { id: 48, name: "Adapted", href: "/adapted", icon: "/images/nav-icons/adapted.jpg" },
    { id: 49, name: "Golfing", href: "/golfing", icon: "/images/nav-icons/golfing.jpg" },
    { id: 50, name: "Surfing", href: "/surfing", icon: "/images/nav-icons/surfing.jpg" },
    { id: 51, name: "Trulli", href: "/trulli", icon: "/images/nav-icons/trulli.jpg" },
    { id: 52, name: "Dammusi", href: "/dammusi", icon: "/images/nav-icons/dammusi.jpg" },
    { id: 53, name: "Ryokans", href: "/ryokans", icon: "/images/nav-icons/ryokans.jpg" },
    { id: 54, name: "Riads", href: "/riads", icon: "/images/nav-icons/riads.jpg" },
    { id: 55, name: "Minsus", href: "/minsus", icon: "/images/nav-icons/minsus.jpg" },
    { id: 56, name: "Desert", href: "/desert", icon: "/images/nav-icons/desert.jpg" },
    { id: 57, name: "Hanoks", href: "/hanoks", icon: "/images/nav-icons/hanoks.jpg" },
    { id: 58, name: "Shepherd's huts", href: "/shepherds-huts", icon: "/images/nav-icons/shepherds-huts.jpg" },
    { id: 59, name: "Campers", href: "/campers", icon: "/images/nav-icons/campers.jpg" },
    { id: 60, name: "Casas particulares", href: "/casas-particulares", icon: "/images/nav-icons/casas-particulares.jpg" },
    { id: 61, name: "Beach", href: "/beach", icon: "/images/nav-icons/beach.jpg" },
    { id: 62, name: "Skiing", href: "/skiing", icon: "/images/nav-icons/skiing.jpg" },
];
